const CHECKED_AT = "2026-07-29";

const LIMITED_RESEARCH =
  "LIMITED-RESEARCH: original paraphrase for this unpublished internal candidate only. Do not copy page text or media, redistribute this record, or release it without a source-specific rights review.";

const UNKNOWN_TRUST_STATES = Object.freeze({
  route_practicality: "UNKNOWN",
  stroller_practicality: "UNKNOWN",
  sensory_conditions: "UNKNOWN",
  quiet_conditions: "UNKNOWN",
  safety: "UNKNOWN",
  caregiver_facility_suitability: "UNKNOWN",
  family_suitability: "UNKNOWN",
});

export const anchorCatalog = [
  { anchor_id: "san-diego-zoo", name: "San Diego Zoo", cluster: "Balboa Park / Zoo", map_position: { x: 67, y: 20 } },
  { anchor_id: "fleet-science-center", name: "Fleet Science Center", cluster: "Balboa Park / Zoo", map_position: { x: 51, y: 31 } },
  { anchor_id: "the-nat", name: "The Nat", cluster: "Balboa Park / Zoo", map_position: { x: 62, y: 34 } },
  { anchor_id: "central-prado", name: "Central Prado / Balboa Park", cluster: "Balboa Park / Zoo", map_position: { x: 45, y: 42 } },
  {
    anchor_id: "new-childrens-museum",
    name: "The New Children's Museum",
    cluster: "Downtown / Waterfront",
    map_position: { x: 66, y: 71 },
  },
  { anchor_id: "waterfront-park", name: "Waterfront Park", cluster: "Downtown / Waterfront", map_position: { x: 52, y: 64 } },
  {
    anchor_id: "san-diego-airport",
    name: "San Diego International Airport",
    cluster: "Downtown / Waterfront",
    map_position: { x: 32, y: 70 },
  },
  { anchor_id: "birch-aquarium", name: "Birch Aquarium", cluster: "La Jolla", map_position: { x: 14, y: 16 } },
  { anchor_id: "la-jolla-shores", name: "La Jolla Shores", cluster: "La Jolla", map_position: { x: 16, y: 30 } },
  { anchor_id: "belmont-park", name: "Belmont Park", cluster: "Mission Bay", map_position: { x: 25, y: 52 } },
  {
    anchor_id: "mission-bay-public-parks",
    name: "Mission Bay public parks",
    cluster: "Mission Bay",
    map_position: { x: 35, y: 44 },
  },
  {
    anchor_id: "old-town-state-park",
    name: "Old Town San Diego State Historic Park",
    cluster: "Old Town / Mission Valley",
    map_position: { x: 40, y: 62 },
  },
  {
    anchor_id: "old-town-transit-center",
    name: "Old Town Transit Center",
    cluster: "Old Town / Mission Valley",
    map_position: { x: 44, y: 55 },
  },
];

const sources = {
  zooAccessibility: {
    owner: "San Diego Zoo Wildlife Alliance",
    url: "https://zoo.sandiegozoo.org/visit/guests-with-disabilities",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  fleetAccessibility: {
    owner: "Fleet Science Center",
    url: "https://www.fleetscience.org/accessibility",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  fleetAccessibilityMorning: {
    owner: "Fleet Science Center",
    url: "https://www.fleetscience.org/events/accessibility-mornings",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  natAccessibility: {
    owner: "San Diego Natural History Museum",
    url: "https://www.sdnhm.org/visit/accessibility/",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  balboaPark: {
    owner: "City of San Diego Parks and Recreation",
    url: "https://www.sandiego.gov/park-and-recreation/parks/regional/balboa",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  newChildrensAccessibility: {
    owner: "The New Children's Museum",
    url: "https://thinkplaycreate.org/visit/accessibility/",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  waterfrontPark: {
    owner: "County of San Diego Parks and Recreation",
    url: "https://www.sdparks.org/content/sdparks/en/park-pages/Waterfront.html",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  sanAccessibility: {
    owner: "San Diego County Regional Airport Authority",
    url: "https://www.san.org/accessibility/",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  sanServices: {
    owner: "San Diego County Regional Airport Authority",
    url: "https://www.san.org/services-and-facilities/",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  birchFaq: {
    owner: "Birch Aquarium at Scripps / UC San Diego",
    url: "https://aquarium.ucsd.edu/plan-your-visit/faqs-and-rules",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  birchKultureCity: {
    owner: "Birch Aquarium at Scripps / UC San Diego",
    url: "https://aquarium.ucsd.edu/newsroom/birch-aquarium-kulturecity-certified",
    evidence_class: "official first party",
    published_or_updated_at: "2025-03-25",
  },
  beachAmenities: {
    owner: "City of San Diego Lifeguard Services",
    url: "https://www.sandiego.gov/lifeguards/safety/bchreg",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  belmontMap: {
    owner: "Belmont Park",
    url: "https://www.belmontpark.com/park-map",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  missionBay: {
    owner: "City of San Diego Parks and Recreation",
    url: "https://www.sandiego.gov/park-and-recreation/parks/regional/missionbay",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  oldTownPark: {
    owner: "California State Parks",
    url: "https://www.parks.ca.gov/?page_id=663",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  oldTownAccess: {
    owner: "California State Parks Accessibility Division",
    url: "https://www.parks.ca.gov/AccessibleFeatures/Details/663",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  mtsStation: {
    owner: "San Diego Metropolitan Transit System",
    url: "https://www.sdmts.com/old-town-transit-center",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  mtsParking: {
    owner: "San Diego Metropolitan Transit System",
    url: "https://www.sdmts.com/transit-services/transit-station-parking",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
  mtsRules: {
    owner: "San Diego Metropolitan Transit System",
    url: "https://www.sdmts.com/rider-info/how-ride/rules-riding",
    evidence_class: "official first party",
    published_or_updated_at: null,
  },
};

const anchorsById = new Map(anchorCatalog.map((anchor) => [anchor.anchor_id, anchor]));

function record({
  record_id,
  anchor_id,
  reset_type,
  source_fact,
  source,
  operational_caveat,
  confidence = "high",
}) {
  const anchor = anchorsById.get(anchor_id);
  if (!anchor) throw new Error(`Unknown atlas anchor: ${anchor_id}`);
  return {
    record_id,
    anchor_id,
    name: anchor.name,
    cluster: anchor.cluster,
    coordinates: {
      lat: null,
      lng: null,
      status: "UNKNOWN",
      source_url: null,
      checked_at: null,
      reuse_status: null,
      license_or_reuse_note: null,
      evidence_reference: null,
    },
    map_position: { ...anchor.map_position },
    reset_type,
    source_fact,
    source_owner: source.owner,
    source_url: source.url,
    source_published_or_updated_at: source.published_or_updated_at,
    checked_at: CHECKED_AT,
    evidence_class: source.evidence_class,
    confidence,
    human_review_status: "needed",
    human_review_evidence: null,
    trust_states: { ...UNKNOWN_TRUST_STATES },
    operational_caveat,
    reuse_status: "internal-research-only",
    reuse_evidence: null,
    license_or_reuse_note: LIMITED_RESEARCH,
    synthetic: false,
  };
}

export const atlasRecords = [
  record({
    record_id: "zoo-mobility-shuttle",
    anchor_id: "san-diego-zoo",
    reset_type: "mobility support",
    source_fact: "The Zoo lists a complimentary in-park ADA shuttle for guests with mobility-related disabilities.",
    source: sources.zooAccessibility,
    operational_caveat: "Confirm operating hours, pickup points, capacity, wait conditions, and whether the service fits the planned route on the visit date.",
  }),
  record({
    record_id: "zoo-wheelchair-rental",
    anchor_id: "san-diego-zoo",
    reset_type: "mobility support",
    source_fact: "Wheelchairs and electric scooters are listed as entrance-area rentals offered on a first-come basis.",
    source: sources.zooAccessibility,
    operational_caveat: "Confirm inventory, current price, reservation rules, size limits, and return requirements before relying on a rental.",
    confidence: "medium",
  }),
  record({
    record_id: "zoo-stroller-device-policy",
    anchor_id: "san-diego-zoo",
    reset_type: "transport constraint",
    source_fact: "The mobility-device policy permits strollers and identifies which assistive devices may enter the grounds.",
    source: sources.zooAccessibility,
    operational_caveat: "Recheck the full device policy and test the exact grades, pathways, elevators, boarding points, and stroller handling needed by the group.",
  }),
  record({
    record_id: "fleet-accessibility-morning",
    anchor_id: "fleet-science-center",
    reset_type: "quiet/sensory support",
    source_fact: "The Fleet schedules Accessibility Mornings before general opening with house lights on and lower soundtrack volume.",
    source: sources.fleetAccessibilityMorning,
    operational_caveat: "Confirm the next date, admission procedure, capacity, exhibit availability, actual conditions, and individual sensory needs.",
    confidence: "medium",
  }),
  record({
    record_id: "fleet-noise-cancelling-devices",
    anchor_id: "fleet-science-center",
    reset_type: "quiet/sensory support",
    source_fact: "Noise-cancelling devices can be requested at the ticket counter or the Dome Theater.",
    source: sources.fleetAccessibility,
    operational_caveat: "Confirm inventory, checkout steps, device fit, cleaning, return point, and whether the device meets the visitor's needs.",
    confidence: "medium",
  }),
  record({
    record_id: "fleet-wheelchair-request",
    anchor_id: "fleet-science-center",
    reset_type: "mobility support",
    source_fact: "A limited number of complimentary wheelchairs can be requested at the ticket counter.",
    source: sources.fleetAccessibility,
    operational_caveat: "Confirm availability, request timing, size, elevator status, restroom access, and the exact path required for the visit.",
    confidence: "medium",
  }),
  record({
    record_id: "nat-wheelchair-request",
    anchor_id: "the-nat",
    reset_type: "mobility support",
    source_fact: "The Nat lists complimentary wheelchairs for request at the Visitor Services Desk, subject to availability.",
    source: sources.natAccessibility,
    operational_caveat: "Confirm inventory, request timing, lift-key needs, elevator status, and the planned exhibit route before relying on this service.",
    confidence: "medium",
  }),
  record({
    record_id: "nat-listening-headsets",
    anchor_id: "the-nat",
    reset_type: "mobility support",
    source_fact: "Infrared listening headsets are listed for lectures and films in the Kaplan Theater.",
    source: sources.natAccessibility,
    operational_caveat: "Confirm device inventory, compatible programs, pickup and return steps, seating, and individual hearing needs.",
    confidence: "medium",
  }),
  record({
    record_id: "nat-north-entrance-parking",
    anchor_id: "the-nat",
    reset_type: "transport constraint",
    source_fact: "The official page identifies the north entrance and ten designated parking spaces across two nearby lots.",
    source: sources.natAccessibility,
    operational_caveat: "Confirm construction, space availability, curb and surface conditions, entrance operation, and the route from the selected space.",
  }),
  record({
    record_id: "prado-free-tram",
    anchor_id: "central-prado",
    reset_type: "mobility support",
    source_fact: "The City lists a free green tram with ramp-equipped vehicles and several central Balboa Park stops.",
    source: sources.balboaPark,
    operational_caveat: "Confirm same-day service, stop locations, ramp operation, capacity, event interruptions, boarding support, and the path beyond each stop.",
    confidence: "medium",
  }),
  record({
    record_id: "prado-tram-central-benches",
    anchor_id: "central-prado",
    reset_type: "public-space reset",
    source_fact: "The City describes benches and shade at Tram Central near Inspiration Point.",
    source: sources.balboaPark,
    operational_caveat: "Verify current seating, shade at the planned time, crowding, weather exposure, tram activity, and individual reset needs.",
    confidence: "medium",
  }),
  record({
    record_id: "prado-visitor-center",
    anchor_id: "central-prado",
    reset_type: "indoor fallback",
    source_fact: "The Balboa Park Visitor Center is listed in the House of Hospitality at the Plaza de Panama tram stop.",
    source: sources.balboaPark,
    operational_caveat: "Confirm opening hours, indoor public access, available assistance, seating, capacity, and whether entry is useful for the planned situation.",
    confidence: "medium",
  }),
  record({
    record_id: "ncm-breathing-room",
    anchor_id: "new-childrens-museum",
    reset_type: "quiet/sensory support",
    source_fact: "The museum lists a Breathing Room on the Main Level.",
    source: sources.newChildrensAccessibility,
    operational_caveat: "Confirm the room's current location, hours, access procedure, occupancy, conditions, supervision needs, and intended use.",
    confidence: "medium",
  }),
  record({
    record_id: "ncm-noise-cancelling-headphones",
    anchor_id: "new-childrens-museum",
    reset_type: "quiet/sensory support",
    source_fact: "Noise-cancelling headphones are listed for request at the Welcome Desk.",
    source: sources.newChildrensAccessibility,
    operational_caveat: "Confirm inventory, fit, checkout and cleaning process, return point, and whether the device meets the visitor's needs.",
    confidence: "medium",
  }),
  record({
    record_id: "ncm-family-restrooms",
    anchor_id: "new-childrens-museum",
    reset_type: "caregiver facility",
    source_fact: "Family unisex restrooms for visitors who need companion assistance are listed on all three museum floors.",
    source: sources.newChildrensAccessibility,
    operational_caveat: "Confirm exact locations, elevator access, current availability, changing equipment, space, and the facility features required by the caregiver.",
  }),
  record({
    record_id: "waterfront-north-restroom",
    anchor_id: "waterfront-park",
    reset_type: "caregiver facility",
    source_fact: "The north recreation area is listed with a restroom and park information booth.",
    source: sources.waterfrontPark,
    operational_caveat: "Confirm current opening, exact location, maintenance status, changing equipment, accessibility features, and any event closure.",
    confidence: "medium",
  }),
  record({
    record_id: "waterfront-south-play-zone",
    anchor_id: "waterfront-park",
    reset_type: "public-space reset",
    source_fact: "The south area is listed with a children's play zone, picnic areas, restrooms, and a snack bar.",
    source: sources.waterfrontPark,
    operational_caveat: "Confirm each feature's current operation, shade, seating, restroom condition, event occupation, and fit for the group's reset needs.",
    confidence: "medium",
  }),
  record({
    record_id: "waterfront-fountain-hours",
    anchor_id: "waterfront-park",
    reset_type: "public-space reset",
    source_fact: "The County publishes daily operating windows for the north and south fountain jets and reflecting pools.",
    source: sources.waterfrontPark,
    operational_caveat: "Recheck the page on the visit date for closure notices, water operation, weather, maintenance, event restrictions, and water-contact decisions.",
    confidence: "medium",
  }),
  record({
    record_id: "san-assist-travel-guide",
    anchor_id: "san-diego-airport",
    reset_type: "mobility support",
    source_fact: "SAN Assist lists day-of-travel guides for travelers with non-visible disabilities, requested at least three business days ahead.",
    source: sources.sanAccessibility,
    operational_caveat: "Confirm eligibility, availability, request acceptance, meeting point, scope of assistance, terminal, flight timing, and traveler-specific needs.",
    confidence: "medium",
  }),
  record({
    record_id: "san-assist-familiarization-tour",
    anchor_id: "san-diego-airport",
    reset_type: "quiet/sensory support",
    source_fact: "SAN Assist lists weekday familiarization tours intended to help travelers practice navigating the airport before travel.",
    source: sources.sanAccessibility,
    operational_caveat: "Request two to three weeks ahead and confirm availability, participants, route, security boundaries, construction, and whether the tour meets the traveler's needs.",
    confidence: "medium",
  }),
  record({
    record_id: "san-lactation-rooms",
    anchor_id: "san-diego-airport",
    reset_type: "caregiver facility",
    source_fact: "The airport lists six post-security lactation and nursing rooms with handwashing stations, outlets, seating, and soft lighting.",
    source: sources.sanServices,
    operational_caveat: "Confirm the current terminal and gate locations, access rules, occupancy, cleanliness, flight-path detour, and any feature the caregiver requires.",
  }),
  record({
    record_id: "birch-sensory-bags",
    anchor_id: "birch-aquarium",
    reset_type: "quiet/sensory support",
    source_fact: "Birch Aquarium's KultureCity notice lists sensory bags with headphones, fidget tools, cue cards, and weighted lap pads.",
    source: sources.birchKultureCity,
    operational_caveat: "Confirm current certification, inventory, checkout, included items, sanitation, return process, and whether the tools meet the visitor's needs.",
    confidence: "medium",
  }),
  record({
    record_id: "birch-social-story",
    anchor_id: "birch-aquarium",
    reset_type: "quiet/sensory support",
    source_fact: "The aquarium's KultureCity notice says its app includes a Social Story for visit preparation.",
    source: sources.birchKultureCity,
    operational_caveat: "Confirm the app and story are current, review the content before travel, and verify that it covers the visitor's planned spaces and needs.",
    confidence: "medium",
  }),
  record({
    record_id: "birch-wheelchair-loan",
    anchor_id: "birch-aquarium",
    reset_type: "mobility support",
    source_fact: "The visitor FAQ lists wheelchairs for loan from Guest Services on a first-come basis.",
    source: sources.birchFaq,
    operational_caveat: "Confirm inventory, size, pickup and return, ramp operation, exhibit access, parking, and the exact route required.",
    confidence: "medium",
  }),
  record({
    record_id: "shores-beach-wheelchairs",
    anchor_id: "la-jolla-shores",
    reset_type: "mobility support",
    source_fact: "City Lifeguard Services lists a limited number of wide-tire beach wheelchairs available from lifeguards.",
    source: sources.beachAmenities,
    operational_caveat: "Confirm lifeguard staffing, inventory, loan rules, fit, transfer support, tide and sand conditions, and the exact beach access point.",
    confidence: "medium",
  }),
  record({
    record_id: "shores-restrooms-showers",
    anchor_id: "la-jolla-shores",
    reset_type: "caregiver facility",
    source_fact: "The City lists public restrooms and outdoor showers at La Jolla Shores.",
    source: sources.beachAmenities,
    operational_caveat: "Confirm exact location, opening, maintenance, changing equipment, water operation, accessibility features, and current beach conditions.",
    confidence: "medium",
  }),
  record({
    record_id: "shores-playground-picnic",
    anchor_id: "la-jolla-shores",
    reset_type: "public-space reset",
    source_fact: "The City lists a public playground and picnic area at La Jolla Shores.",
    source: sources.beachAmenities,
    operational_caveat: "Confirm which park area contains each feature, current condition, shade, seating, crowding, parking, and fit for the group's reset needs.",
    confidence: "medium",
  }),
  record({
    record_id: "belmont-first-aid",
    anchor_id: "belmont-park",
    reset_type: "caregiver facility",
    source_fact: "Belmont Park's official map identifies a First Aid and AED point.",
    source: sources.belmontMap,
    operational_caveat: "Confirm the current location, operating coverage, staff availability, scope of help, emergency procedure, and any medical needs before visiting.",
    confidence: "medium",
  }),
  record({
    record_id: "belmont-public-restrooms",
    anchor_id: "belmont-park",
    reset_type: "caregiver facility",
    source_fact: "Belmont Park's official map identifies public restrooms.",
    source: sources.belmontMap,
    operational_caveat: "Confirm exact locations, hours, changing equipment, accessibility features, maintenance, crowding, and the caregiver's required facilities.",
    confidence: "medium",
  }),
  record({
    record_id: "belmont-guest-services-lockers",
    anchor_id: "belmont-park",
    reset_type: "public-space reset",
    source_fact: "The official map identifies Guest Services and lockers or storage.",
    source: sources.belmontMap,
    operational_caveat: "Confirm location, hours, locker dimensions, price, payment, availability, prohibited items, and whether Guest Services can address the planned need.",
    confidence: "medium",
  }),
  record({
    record_id: "mission-bay-restrooms-showers",
    anchor_id: "mission-bay-public-parks",
    reset_type: "caregiver facility",
    source_fact: "The City states that public restrooms and showers are available within Mission Bay Park.",
    source: sources.missionBay,
    operational_caveat: "Select an exact park before use, then confirm the nearest facility, opening, maintenance, changing equipment, access, and closure status.",
    confidence: "medium",
  }),
  record({
    record_id: "mission-bay-paths-playgrounds",
    anchor_id: "mission-bay-public-parks",
    reset_type: "public-space reset",
    source_fact: "The City lists bike and walking paths plus children's playgrounds within Mission Bay Park.",
    source: sources.missionBay,
    operational_caveat: "Select an exact park and verify the path surface, playground location, weather exposure, parking, crowding, construction, and reset fit.",
    confidence: "medium",
  }),
  record({
    record_id: "mission-bay-closure-check",
    anchor_id: "mission-bay-public-parks",
    reset_type: "transport constraint",
    source_fact: "The Mission Bay page routes visitors to the County's current beach and bay status source for closure information.",
    source: sources.missionBay,
    operational_caveat: "Check the linked status source on the visit date and verify the exact park, shoreline, water condition, access route, and planned activity.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-visitor-center-hours",
    anchor_id: "old-town-state-park",
    reset_type: "indoor fallback",
    source_fact: "California State Parks lists the Visitor Center and select museums with a daily 10 a.m. to 5 p.m. operating window.",
    source: sources.oldTownPark,
    operational_caveat: "Recheck the dynamic restrictions panel, holiday closures, exact museum openings, capacity, indoor seating, and the planned visit date.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-route-guide-barriers",
    anchor_id: "old-town-state-park",
    reset_type: "transport constraint",
    source_fact: "The official features page points to route guides and flags remaining stairs, narrow doors, high thresholds, slopes, and cross-slope barriers.",
    source: sources.oldTownAccess,
    operational_caveat: "Obtain the current guide and test the exact entrance and route; do not infer wheelchair or stroller practicality from the general description.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-restroom-locations",
    anchor_id: "old-town-state-park",
    reset_type: "caregiver facility",
    source_fact: "The official features page identifies restroom locations on Wallace, Calhoun, and Mason streets.",
    source: sources.oldTownAccess,
    operational_caveat: "Confirm each facility's current opening, entrance, space, changing equipment, maintenance, route barriers, and caregiver requirements.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-transit-hours",
    anchor_id: "old-town-transit-center",
    reset_type: "transport constraint",
    source_fact: "MTS lists Old Town Transit Center at 4009 Taylor Street with station hours from 6 a.m. to 9 p.m.",
    source: sources.mtsStation,
    operational_caveat: "Confirm current station access hours, service alerts, entrances, platform access, construction, staffing, and the exact transfer route.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-transit-lines-parking",
    anchor_id: "old-town-transit-center",
    reset_type: "transport constraint",
    source_fact: "MTS lists Green and UC San Diego Blue Line service plus 412 transit parking spaces at Old Town.",
    source: sources.mtsParking,
    operational_caveat: "Recheck line service, parking availability and limits, closures, elevators, platform changes, and the full origin-to-destination transfer.",
    confidence: "medium",
  }),
  record({
    record_id: "old-town-stroller-policy",
    anchor_id: "old-town-transit-center",
    reset_type: "transport constraint",
    source_fact: "MTS bus policy requires removing a child from a stroller before departure and storing the stroller outside aisles, doors, and exits.",
    source: sources.mtsRules,
    operational_caveat: "Recheck the complete bus and Trolley rules, vehicle type, dimensions, capacity, boarding assistance, transfers, and trip-date service.",
  }),
];
