export const syntheticAtlasRecords = [
  {
    anchor_id: "fixture-balboa-indoor",
    name: "Synthetic Balboa indoor anchor",
    cluster: "Balboa Park / Zoo",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 30, y: 24 },
    reset_type: "indoor fallback",
    source_fact: "Synthetic fixture showing where a short, source-bounded facility paraphrase would appear.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Verify the exact facility, operating date, capacity, conditions, and family-specific usefulness before any real release.",
    license_or_reuse_note: "No real source material or coordinates are included; reuse rights remain untested.",
    synthetic: true,
  },
  {
    anchor_id: "fixture-balboa-sensory",
    name: "Synthetic Balboa support anchor",
    cluster: "Balboa Park / Zoo",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 45, y: 34 },
    reset_type: "quiet/sensory support",
    source_fact: "Synthetic fixture demonstrating an explicit support-program field without asserting visit conditions.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Verify program date, capacity, actual conditions, and individual needs; an offered program does not establish suitability.",
    license_or_reuse_note: "No program text or source-owned material is ingested.",
    synthetic: true,
  },
  {
    anchor_id: "fixture-waterfront-caregiver",
    name: "Synthetic waterfront caregiver anchor",
    cluster: "Downtown / Waterfront",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 62, y: 68 },
    reset_type: "caregiver facility",
    source_fact: "Synthetic fixture showing how a facility-presence claim would remain unconfirmed until explicitly sourced.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Verify exact facility type, terminal or building location, access rules, hours, and current availability.",
    license_or_reuse_note: "Demonstration text only; no real facility record is redistributed.",
    synthetic: true,
  },
  {
    anchor_id: "fixture-la-jolla-mobility",
    name: "Synthetic La Jolla mobility anchor",
    cluster: "La Jolla",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 74, y: 20 },
    reset_type: "mobility support",
    source_fact: "Synthetic fixture demonstrating a sourced-attribute slot without inferring route practicality.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Test the exact route, surface, grade, elevator or ramp state, stroller handling, and visit-date conditions.",
    license_or_reuse_note: "No official route, map, or accessibility content is copied.",
    synthetic: true,
  },
  {
    anchor_id: "fixture-mission-bay-public",
    name: "Synthetic Mission Bay public-space anchor",
    cluster: "Mission Bay",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 20, y: 72 },
    reset_type: "public-space reset",
    source_fact: "Synthetic fixture illustrating a public-space record before real open-data geometry is authorized and ingested.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Recheck closures, facilities, weather exposure, crowding, current conditions, and individual reset needs.",
    license_or_reuse_note: "No City geometry or page content is included in this fixture.",
    synthetic: true,
  },
  {
    anchor_id: "fixture-old-town-transport",
    name: "Synthetic Old Town transport anchor",
    cluster: "Old Town / Mission Valley",
    coordinates: { lat: null, lng: null, status: "withheld-synthetic-fixture" },
    map_position: { x: 48, y: 82 },
    reset_type: "transport constraint",
    source_fact: "Synthetic fixture demonstrating where a current operating rule could be paraphrased and dated.",
    source_owner: "Synthetic fixture — no source owner",
    source_url: null,
    source_published_or_updated_at: null,
    checked_at: "2026-07-17",
    evidence_class: "synthetic fixture",
    confidence: "UNKNOWN",
    human_review_status: "needed",
    operational_caveat: "Verify the current rule, exact station path, transfer steps, capacity, stroller constraints, and trip-date service.",
    license_or_reuse_note: "No agency rule text, schedule, or map is reproduced.",
    synthetic: true,
  },
];
